### PR TITLE
Add crash and crashWith

### PR DESCRIPTION
**Pull request by paf31**
I figured these might make useful alternatives to the usual exhaustivity error message.

### CODE REVIEW

**Comment by garyb** [comment]
Good thinking :+1:

**Comment by garyb** [comment]
Maybe we want unsafe versions of these too, without the constraint? So we can replace the `unsafeThrow` things we have in places currently where we're manually verifying something is not partial? I guess `unsafePartial` does the same job, but having another option for defining "it's-not-partial-honest" functions with a better fail error might be useful.

**Comment by paf31** [comment]
How's this?

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
Ok, how do I version this again?

**Comment by garyb** [comment]
`v1.1.0`, as it's backwards compatible new features.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
