### PR TITLE
Add guide

### PR DESCRIPTION
**Pull request by anttih**
I "upgraded" the guide to use `Effect`.

@hdgarrood do you want more credit for writing the guide than the mention in the commit message?

### CODE REVIEW

**Comment by hdgarrood** [comment]
I’m fine with a mention in the commit message - thanks for asking  :)

I intended in that issue on the docs repo that the docs should go into the source file so that they show up on pursuit. That would be a lot easier to find than a markdown file in this repo, I think.

**Comment by anttih** [comment]
So just dump it at the top of `Partial.purs`? There's also `Partial/Unsafe.purs` which is related. I'm not sure I like putting it all in the source code. 

We will also need to update this link, btw https://github.com/purescript/purescript/blob/46a5449cb860008ff3b4048a0446415c285eef17/src/Language/PureScript/Docs/Prim.hs#L330

but then it gets a little weird linking to library documentation from the purescript codebase.

**Comment by hdgarrood** [comment]
What's wrong with putting it all in the source code? Other than, as you said,

> it gets a little weird linking to library documentation from the purescript codebase,

which is indeed a good point. It's just that I think it should be the case that if I want to find out about the Partial type class, I should be able to do so -- and in particular, I should be able to find this guide -- by searching "Partial" in Pursuit.

**Comment by hdgarrood** [comment]
I think we're going to have an issue with certain docs referencing other docs which they perhaps shouldn't whatever we do, though: if we put the guide here, then we'll want to link to library documentation from the purescript codebase, but if we try to put the guide in the Prim docs, we'll have discussion of functions from this library, like `unsafePartial`, in the compiler repo, which would be bad as they could go out of date.

I think putting it here is probably the best option, because we can say "see the purescript-partial library" in the Prim docs, and then we wouldn't need to worry about that going out of date unless we renamed this library or moved the functions around, which I think is unlikely to happen often.

**Comment by hdgarrood** [comment]
Also, one other thing has just occurred to me: it's also a little awkward to have to choose one of the two modules this library provides to put this guide in, if it does go into the source code. However, there is another option: we could put this guide in the README, since READMEs show up on Pursuit as well. We could also add a little note in each module saying "see the README" so that if someone looks up "unsafePartial" on Pursuit and goes straight to the module docs page, they won't miss that guide.

**Comment by anttih** [comment]
README makes sense, I was going to suggest the same. I've updated the PR.

**Pull request merged**
